<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Suite set up is getting ready]]>
    </line>
    <line>
      <![CDATA[Suite set up is success]]>
    </line>
    <line>
      <![CDATA[Browser is getting ready]]>
    </line>
    <line>
      <![CDATA[Browser set up is success]]>
    </line>
    <line>
      <![CDATA[Test is completed and reports is generated]]>
    </line>
  </reporter-output>
  <suite started-at="2024-03-07T13:07:42 GST" name="Default suite" finished-at="2024-03-07T13:07:46 GST" duration-ms="4141">
    <groups>
    </groups>
    <test started-at="2024-03-07T13:07:42 GST" name="Default test" finished-at="2024-03-07T13:07:46 GST" duration-ms="4141">
      <class name="com.learnautomation.testcases.LoginTestVtiger">
        <test-method is-config="true" signature="setupSuite()[pri:0, instance:com.learnautomation.testcases.LoginTestVtiger@5ffead27]" started-at="2024-03-07T13:07:41 GST" name="setupSuite" finished-at="2024-03-07T13:07:42 GST" duration-ms="236" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Suite set up is getting ready]]>
            </line>
            <line>
              <![CDATA[Suite set up is success]]>
            </line>
          </reporter-output>
        </test-method> <!-- setupSuite -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.learnautomation.testcases.LoginTestVtiger@5ffead27]" started-at="2024-03-07T13:07:42 GST" name="setup" finished-at="2024-03-07T13:07:45 GST" duration-ms="3150" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Browser is getting ready]]>
            </line>
            <line>
              <![CDATA[Browser set up is success]]>
            </line>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginApp()[pri:0, instance:com.learnautomation.testcases.LoginTestVtiger@5ffead27]" started-at="2024-03-07T13:07:45 GST" name="loginApp" finished-at="2024-03-07T13:07:45 GST" duration-ms="41" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.learnautomation.testcases.LoginTestVtiger.loginApp(LoginTestVtiger.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginApp -->
        <test-method is-config="true" signature="teardownmethod(org.testng.ITestResult)[pri:0, instance:com.learnautomation.testcases.LoginTestVtiger@5ffead27]" started-at="2024-03-07T13:07:45 GST" name="teardownmethod" finished-at="2024-03-07T13:07:46 GST" duration-ms="703" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginApp status=FAILURE method=LoginTestVtiger.loginApp()[pri:0, instance:com.learnautomation.testcases.LoginTestVtiger@5ffead27] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test is completed and reports is generated]]>
            </line>
          </reporter-output>
        </test-method> <!-- teardownmethod -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.learnautomation.testcases.LoginTestVtiger@5ffead27]" started-at="2024-03-07T13:07:46 GST" name="teardown" finished-at="2024-03-07T13:07:46 GST" duration-ms="213" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.learnautomation.testcases.LoginTestVtiger -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
